name = "Avicenna"
license = "MIT"
licenselink = "https://github.com/lcpz/avicenna/blob/master/LICENSE"
description = "A minimal, simple, and responsive academic page"
homepage = "https://github.com/lcpz/avicenna"
tags = ["academic", "personal", "minimal", "minimalist", "clean", "responsive", "simple"]
features = ["Academic", "Responsive", "Clean And Minimal", "Social Media Links"]
min_version = "0.41"

[author]
  name = "Luca Capezzuto"
  homepage = "https://lcpz.gitlab.io""

[original]
  name = "Hadi Sinaee"
  homepage = "http://ce.sharif.edu/~sinaee/"
  repo = "https://github.com/hadisinaee/avicenna"
